// Generated by levelplay_tools_node on 2026-09-30. App keys and ad unit IDs are public identifiers, not secrets.
import 'dart:io' show Platform;

/// Compiled LevelPlay identifiers, before any Remote Config override.
class LevelPlayIds {
  LevelPlayIds._();

  static const String appKeyAndroid = '286d22c95';
  static const String appKeyIos = '286d2661d';
  static const String bannerAndroid = 'jb31fqpa4bvfm3d8';
  static const String bannerIos = 'yiyb48zj4gxxr8ms';
  static const String interstitialAndroid = 'i84sy4y6e83ghxnt';
  static const String interstitialIos = 'ssodjiwc1v2rmuiu';
  static const String nativeAndroid = 'juhjifqa745x1u1y';
  static const String nativeIos = 'pb1jjvy2day2rz2t';
  static const String rewardedAndroid = '8zbj7ngk9koobeel';
  static const String rewardedIos = '7ms0f73ajixdf2e3';

  static const LevelPlayPlacementIds placements = LevelPlayPlacementIds(
    appKeyAndroid: appKeyAndroid,
    appKeyIos: appKeyIos,
    bannerAndroid: bannerAndroid,
    bannerIos: bannerIos,
    interstitialAndroid: interstitialAndroid,
    interstitialIos: interstitialIos,
    rewardedAndroid: rewardedAndroid,
    rewardedIos: rewardedIos,
    nativeAndroid: nativeAndroid,
    nativeIos: nativeIos,
  );

  static String get appKey => Platform.isIOS ? appKeyIos : appKeyAndroid;
  static String get banner => Platform.isIOS ? bannerIos : bannerAndroid;
  static String get interstitial =>
      Platform.isIOS ? interstitialIos : interstitialAndroid;
  static String get native => Platform.isIOS ? nativeIos : nativeAndroid;
  static String get rewarded => Platform.isIOS ? rewardedIos : rewardedAndroid;
}

/// App keys and ad unit ids for one process.
///
/// A published Remote Config string replaces the matching compiled id.
/// Empty and non-remote values keep [LevelPlayIds.placements].
class LevelPlayPlacementIds {
  const LevelPlayPlacementIds({
    required this.appKeyAndroid,
    required this.appKeyIos,
    required this.bannerAndroid,
    required this.bannerIos,
    required this.interstitialAndroid,
    required this.interstitialIos,
    required this.rewardedAndroid,
    required this.rewardedIos,
    required this.nativeAndroid,
    required this.nativeIos,
  });

  final String appKeyAndroid;
  final String appKeyIos;
  final String bannerAndroid;
  final String bannerIos;
  final String interstitialAndroid;
  final String interstitialIos;
  final String rewardedAndroid;
  final String rewardedIos;
  final String nativeAndroid;
  final String nativeIos;
}
