// Generated by levelplay_tools_node on 2026-09-30. App keys and ad unit IDs are public identifiers, not secrets.
import 'dart:io' show Platform;

class LevelPlayIds {
  LevelPlayIds._();

  static String get appKey => Platform.isIOS ? '286d2661d' : '286d22c95';
  static String get banner => Platform.isIOS ? 'yiyb48zj4gxxr8ms' : 'jb31fqpa4bvfm3d8';
  static String get interstitial => Platform.isIOS ? 'ssodjiwc1v2rmuiu' : 'i84sy4y6e83ghxnt';
  static String get native => Platform.isIOS ? 'pb1jjvy2day2rz2t' : 'juhjifqa745x1u1y';
  static String get rewarded => Platform.isIOS ? '7ms0f73ajixdf2e3' : '8zbj7ngk9koobeel';
}
